"""
FastAPI routes for delegation API.

Handles requests from small nodes to delegate PoC computation.
"""

from fastapi import APIRouter, Request, HTTPException, Query

from pow.service.delegation.server import DelegationManager
from pow.service.delegation.types import (
    DelegationStartRequest,
    DelegationStartResponse,
    DelegationBatchResponse,
    DelegationStopRequest,
    DelegationStopResponse,
    DelegationStatus,
)
from common.logger import create_logger

logger = create_logger(__name__)

router = APIRouter(
    tags=["Delegation API"],
)


@router.post(
    "/start",
    response_model=DelegationStartResponse,
    status_code=200,
)
async def start_delegation(
    request: Request,
    start_request: DelegationStartRequest,
):
    """
    Start a new delegation session.

    Small node sends this request to big node to initiate PoC computation
    delegation. Big node creates a session and starts generating batches.

    Args:
        request: FastAPI request
        start_request: Delegation parameters

    Returns:
        DelegationStartResponse with session_id and GPU count

    Raises:
        HTTPException: If auth token invalid or max sessions reached
    """
    manager: DelegationManager = request.app.state.delegation_manager

    try:
        session = manager.create_session(start_request)

        return DelegationStartResponse(
            session_id=session.session_id,
            status=session.status,
            message=f"Session created with {session.get_gpu_count()} GPU groups",
            gpu_count=session.get_gpu_count(),
        )

    except ValueError as e:
        logger.error(f"Failed to create session: {e}")
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error(f"Unexpected error creating session: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")


@router.get(
    "/batches/{session_id}",
    response_model=DelegationBatchResponse,
    status_code=200,
)
async def get_batches(
    request: Request,
    session_id: str,
    auth_token: str = Query(..., description="Authentication token"),
):
    """
    Get generated batches from delegation session.

    Small node polls this endpoint to retrieve batches generated by big node.
    Batches are removed from buffer after retrieval.

    Args:
        request: FastAPI request
        session_id: Session identifier
        auth_token: Authentication token

    Returns:
        DelegationBatchResponse with batches and session status

    Raises:
        HTTPException: If auth token invalid or session not found
    """
    manager: DelegationManager = request.app.state.delegation_manager

    try:
        batches = manager.get_batches(session_id, auth_token)
        session = manager.get_session(session_id)

        if not session:
            raise HTTPException(status_code=404, detail="Session not found")

        return DelegationBatchResponse(
            session_id=session_id,
            batches=batches,
            session_active=session.status == DelegationStatus.GENERATING,
            status=session.status,
            total_batches_generated=session.total_generated,
        )

    except ValueError as e:
        logger.error(f"Failed to get batches: {e}")
        raise HTTPException(status_code=400, detail=str(e))
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Unexpected error getting batches: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")


@router.post(
    "/stop",
    response_model=DelegationStopResponse,
    status_code=200,
)
async def stop_delegation(
    request: Request,
    stop_request: DelegationStopRequest,
):
    """
    Stop a delegation session.

    Small node sends this request to terminate the delegation session
    on big node. Big node stops generation and cleans up resources.

    Args:
        request: FastAPI request
        stop_request: Stop request with session_id and auth_token

    Returns:
        DelegationStopResponse with final session statistics

    Raises:
        HTTPException: If auth token invalid or session not found
    """
    manager: DelegationManager = request.app.state.delegation_manager

    try:
        session = manager.stop_session(
            stop_request.session_id,
            stop_request.auth_token,
        )

        return DelegationStopResponse(
            session_id=session.session_id,
            status=session.status,
            message="Session stopped successfully",
            total_batches_generated=session.total_generated,
        )

    except ValueError as e:
        logger.error(f"Failed to stop session: {e}")
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error(f"Unexpected error stopping session: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")


@router.get(
    "/status",
    status_code=200,
)
async def get_status(request: Request):
    """
    Get delegation manager status.

    Returns information about all active sessions and manager state.
    Useful for monitoring and debugging.

    Args:
        request: FastAPI request

    Returns:
        Dictionary with manager status
    """
    manager: DelegationManager = request.app.state.delegation_manager

    try:
        return manager.get_status()

    except Exception as e:
        logger.error(f"Error getting status: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")
