// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/participant.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ParticipantStatus int32

const (
	ParticipantStatus_UNSPECIFIED ParticipantStatus = 0
	ParticipantStatus_ACTIVE      ParticipantStatus = 1
	ParticipantStatus_INACTIVE    ParticipantStatus = 2
	ParticipantStatus_INVALID     ParticipantStatus = 3
	ParticipantStatus_RAMPING     ParticipantStatus = 4
)

var ParticipantStatus_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "ACTIVE",
	2: "INACTIVE",
	3: "INVALID",
	4: "RAMPING",
}

var ParticipantStatus_value = map[string]int32{
	"UNSPECIFIED": 0,
	"ACTIVE":      1,
	"INACTIVE":    2,
	"INVALID":     3,
	"RAMPING":     4,
}

func (x ParticipantStatus) String() string {
	return proto.EnumName(ParticipantStatus_name, int32(x))
}

func (ParticipantStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2bc555767052d80, []int{0}
}

type Participant struct {
	Index                        string             `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Address                      string             `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Weight                       int32              `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	JoinTime                     int64              `protobuf:"varint,4,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	JoinHeight                   int64              `protobuf:"varint,5,opt,name=join_height,json=joinHeight,proto3" json:"join_height,omitempty"`
	LastInferenceTime            int64              `protobuf:"varint,6,opt,name=last_inference_time,json=lastInferenceTime,proto3" json:"last_inference_time,omitempty"`
	InferenceUrl                 string             `protobuf:"bytes,7,opt,name=inference_url,json=inferenceUrl,proto3" json:"inference_url,omitempty"`
	Status                       ParticipantStatus  `protobuf:"varint,8,opt,name=status,proto3,enum=inference.inference.ParticipantStatus" json:"status,omitempty"`
	CoinBalance                  int64              `protobuf:"varint,9,opt,name=coin_balance,json=coinBalance,proto3" json:"coin_balance,omitempty"`
	ValidatorKey                 string             `protobuf:"bytes,10,opt,name=validator_key,json=validatorKey,proto3" json:"validator_key,omitempty"`
	ConsecutiveInvalidInferences int64              `protobuf:"varint,11,opt,name=consecutive_invalid_inferences,json=consecutiveInvalidInferences,proto3" json:"consecutive_invalid_inferences,omitempty"`
	WorkerPublicKey              string             `protobuf:"bytes,12,opt,name=worker_public_key,json=workerPublicKey,proto3" json:"worker_public_key,omitempty"`
	EpochsCompleted              uint32             `protobuf:"varint,13,opt,name=epochs_completed,json=epochsCompleted,proto3" json:"epochs_completed,omitempty"`
	CurrentEpochStats            *CurrentEpochStats `protobuf:"bytes,14,opt,name=current_epoch_stats,json=currentEpochStats,proto3" json:"current_epoch_stats,omitempty"`
}

func (m *Participant) Reset()         { *m = Participant{} }
func (m *Participant) String() string { return proto.CompactTextString(m) }
func (*Participant) ProtoMessage()    {}
func (*Participant) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2bc555767052d80, []int{0}
}
func (m *Participant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Participant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Participant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Participant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participant.Merge(m, src)
}
func (m *Participant) XXX_Size() int {
	return m.Size()
}
func (m *Participant) XXX_DiscardUnknown() {
	xxx_messageInfo_Participant.DiscardUnknown(m)
}

var xxx_messageInfo_Participant proto.InternalMessageInfo

func (m *Participant) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Participant) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Participant) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Participant) GetJoinTime() int64 {
	if m != nil {
		return m.JoinTime
	}
	return 0
}

func (m *Participant) GetJoinHeight() int64 {
	if m != nil {
		return m.JoinHeight
	}
	return 0
}

func (m *Participant) GetLastInferenceTime() int64 {
	if m != nil {
		return m.LastInferenceTime
	}
	return 0
}

func (m *Participant) GetInferenceUrl() string {
	if m != nil {
		return m.InferenceUrl
	}
	return ""
}

func (m *Participant) GetStatus() ParticipantStatus {
	if m != nil {
		return m.Status
	}
	return ParticipantStatus_UNSPECIFIED
}

func (m *Participant) GetCoinBalance() int64 {
	if m != nil {
		return m.CoinBalance
	}
	return 0
}

func (m *Participant) GetValidatorKey() string {
	if m != nil {
		return m.ValidatorKey
	}
	return ""
}

func (m *Participant) GetConsecutiveInvalidInferences() int64 {
	if m != nil {
		return m.ConsecutiveInvalidInferences
	}
	return 0
}

func (m *Participant) GetWorkerPublicKey() string {
	if m != nil {
		return m.WorkerPublicKey
	}
	return ""
}

func (m *Participant) GetEpochsCompleted() uint32 {
	if m != nil {
		return m.EpochsCompleted
	}
	return 0
}

func (m *Participant) GetCurrentEpochStats() *CurrentEpochStats {
	if m != nil {
		return m.CurrentEpochStats
	}
	return nil
}

type CurrentEpochStats struct {
	InferenceCount        uint64 `protobuf:"varint,1,opt,name=inference_count,json=inferenceCount,proto3" json:"inference_count,omitempty"`
	MissedRequests        uint64 `protobuf:"varint,2,opt,name=missed_requests,json=missedRequests,proto3" json:"missed_requests,omitempty"`
	EarnedCoins           uint64 `protobuf:"varint,3,opt,name=earned_coins,json=earnedCoins,proto3" json:"earned_coins,omitempty"`
	RewardedCoins         uint64 `protobuf:"varint,4,opt,name=rewarded_coins,json=rewardedCoins,proto3" json:"rewarded_coins,omitempty"`
	BurnedCoins           uint64 `protobuf:"varint,5,opt,name=burned_coins,json=burnedCoins,proto3" json:"burned_coins,omitempty"`
	ValidatedInferences   uint64 `protobuf:"varint,6,opt,name=validated_inferences,json=validatedInferences,proto3" json:"validated_inferences,omitempty"`
	InvalidatedInferences uint64 `protobuf:"varint,7,opt,name=invalidated_inferences,json=invalidatedInferences,proto3" json:"invalidated_inferences,omitempty"`
}

func (m *CurrentEpochStats) Reset()         { *m = CurrentEpochStats{} }
func (m *CurrentEpochStats) String() string { return proto.CompactTextString(m) }
func (*CurrentEpochStats) ProtoMessage()    {}
func (*CurrentEpochStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2bc555767052d80, []int{1}
}
func (m *CurrentEpochStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentEpochStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentEpochStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentEpochStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentEpochStats.Merge(m, src)
}
func (m *CurrentEpochStats) XXX_Size() int {
	return m.Size()
}
func (m *CurrentEpochStats) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentEpochStats.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentEpochStats proto.InternalMessageInfo

func (m *CurrentEpochStats) GetInferenceCount() uint64 {
	if m != nil {
		return m.InferenceCount
	}
	return 0
}

func (m *CurrentEpochStats) GetMissedRequests() uint64 {
	if m != nil {
		return m.MissedRequests
	}
	return 0
}

func (m *CurrentEpochStats) GetEarnedCoins() uint64 {
	if m != nil {
		return m.EarnedCoins
	}
	return 0
}

func (m *CurrentEpochStats) GetRewardedCoins() uint64 {
	if m != nil {
		return m.RewardedCoins
	}
	return 0
}

func (m *CurrentEpochStats) GetBurnedCoins() uint64 {
	if m != nil {
		return m.BurnedCoins
	}
	return 0
}

func (m *CurrentEpochStats) GetValidatedInferences() uint64 {
	if m != nil {
		return m.ValidatedInferences
	}
	return 0
}

func (m *CurrentEpochStats) GetInvalidatedInferences() uint64 {
	if m != nil {
		return m.InvalidatedInferences
	}
	return 0
}

func init() {
	proto.RegisterEnum("inference.inference.ParticipantStatus", ParticipantStatus_name, ParticipantStatus_value)
	proto.RegisterType((*Participant)(nil), "inference.inference.Participant")
	proto.RegisterType((*CurrentEpochStats)(nil), "inference.inference.CurrentEpochStats")
}

func init() {
	proto.RegisterFile("inference/inference/participant.proto", fileDescriptor_d2bc555767052d80)
}

var fileDescriptor_d2bc555767052d80 = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0xc7, 0x9b, 0x2d, 0x6d, 0xb7, 0x93, 0xbe, 0xba, 0x7b, 0xa6, 0x48, 0xcf, 0xa3, 0x3c, 0xdd,
	0xd0, 0xa0, 0xec, 0xa2, 0x13, 0xa0, 0xdd, 0x22, 0x6d, 0x5d, 0x81, 0x08, 0x28, 0x55, 0xf6, 0x22,
	0xc4, 0x4d, 0x94, 0x3a, 0x66, 0x35, 0x4b, 0x93, 0x60, 0x3b, 0x7b, 0xf9, 0x16, 0x7c, 0x20, 0x3e,
	0x00, 0x97, 0xbb, 0xe4, 0x12, 0x6d, 0xe2, 0x7b, 0x20, 0xdb, 0x6d, 0x5a, 0x36, 0xb8, 0xf3, 0xf9,
	0xfd, 0xff, 0xe7, 0xf8, 0xd8, 0xc7, 0x32, 0x6c, 0xd1, 0xf8, 0x23, 0x61, 0x24, 0xc6, 0x64, 0x67,
	0xbe, 0x4a, 0x03, 0x26, 0x28, 0xa6, 0x69, 0x10, 0x8b, 0x6e, 0xca, 0x12, 0x91, 0xa0, 0x56, 0x2e,
	0x76, 0xf3, 0xd5, 0xe6, 0x4f, 0x13, 0xac, 0xe1, 0xdc, 0x8a, 0xd6, 0xa0, 0x48, 0xe3, 0x90, 0x5c,
	0xda, 0x46, 0xdb, 0xe8, 0xac, 0x7a, 0x3a, 0x40, 0x36, 0x94, 0x83, 0x30, 0x64, 0x84, 0x73, 0x7b,
	0x49, 0xf1, 0x59, 0x88, 0xd6, 0xa1, 0x74, 0x41, 0xe8, 0xe9, 0x58, 0xd8, 0xcb, 0x6d, 0xa3, 0x53,
	0xf4, 0xa6, 0x11, 0xfa, 0x17, 0x56, 0x3f, 0x25, 0x34, 0xf6, 0x05, 0x9d, 0x10, 0xdb, 0x6c, 0x1b,
	0x9d, 0x65, 0x6f, 0x45, 0x82, 0x23, 0x3a, 0x21, 0xe8, 0x7f, 0xb0, 0x94, 0x38, 0xd6, 0x99, 0x45,
	0x25, 0x83, 0x44, 0xaf, 0x74, 0x76, 0x17, 0x5a, 0x51, 0xc0, 0x85, 0x9f, 0xf7, 0xa9, 0xeb, 0x94,
	0x94, 0xb1, 0x29, 0x25, 0x77, 0xa6, 0xa8, 0x82, 0x0f, 0xa0, 0x3a, 0xb7, 0x66, 0x2c, 0xb2, 0xcb,
	0xaa, 0xcb, 0x4a, 0x0e, 0x8f, 0x59, 0x84, 0x9e, 0x43, 0x89, 0x8b, 0x40, 0x64, 0xdc, 0x5e, 0x69,
	0x1b, 0x9d, 0xda, 0xd3, 0x87, 0xdd, 0x3f, 0x5c, 0x48, 0x77, 0xe1, 0x32, 0x0e, 0x95, 0xdb, 0x9b,
	0x66, 0xa1, 0x0d, 0xa8, 0x60, 0xd9, 0xf5, 0x28, 0x88, 0x82, 0x18, 0x13, 0x7b, 0x55, 0x75, 0x63,
	0x49, 0xb6, 0xaf, 0x91, 0xec, 0xe3, 0x3c, 0x88, 0x68, 0x18, 0x88, 0x84, 0xf9, 0x67, 0xe4, 0xca,
	0x06, 0xdd, 0x47, 0x0e, 0x5f, 0x93, 0x2b, 0x74, 0x00, 0x0e, 0x4e, 0x62, 0x4e, 0x70, 0x26, 0xe8,
	0x39, 0xf1, 0x69, 0xac, 0xd4, 0xf9, 0x59, 0xb9, 0x6d, 0xa9, 0xca, 0xff, 0x2d, 0xb8, 0x5c, 0x6d,
	0xca, 0x4f, 0xcd, 0xd1, 0x36, 0x34, 0x2f, 0x12, 0x76, 0x46, 0x98, 0x9f, 0x66, 0xa3, 0x88, 0x62,
	0xb5, 0x5d, 0x45, 0x6d, 0x57, 0xd7, 0xc2, 0x50, 0x71, 0xb9, 0xe3, 0x63, 0x68, 0x90, 0x34, 0xc1,
	0x63, 0xee, 0xe3, 0x64, 0x92, 0x46, 0x44, 0x90, 0xd0, 0xae, 0xb6, 0x8d, 0x4e, 0xd5, 0xab, 0x6b,
	0xde, 0x9b, 0x61, 0x74, 0x02, 0x2d, 0x9c, 0x31, 0x46, 0x62, 0xe1, 0x2b, 0xc9, 0x97, 0x87, 0xe7,
	0x76, 0xad, 0x6d, 0x74, 0xac, 0xbf, 0xdc, 0x58, 0x4f, 0xfb, 0xfb, 0xd2, 0x2e, 0xaf, 0x8c, 0x7b,
	0x4d, 0x7c, 0x17, 0x6d, 0x7e, 0x5d, 0x82, 0xe6, 0x3d, 0x23, 0x7a, 0x04, 0xf5, 0xf9, 0xdc, 0x70,
	0x92, 0xc5, 0x42, 0xbd, 0x3b, 0xd3, 0xab, 0xe5, 0xb8, 0x27, 0xa9, 0x34, 0x4e, 0x28, 0xe7, 0x24,
	0xf4, 0x19, 0xf9, 0x9c, 0x11, 0x2e, 0xf4, 0x43, 0x34, 0xbd, 0x9a, 0xc6, 0xde, 0x94, 0xca, 0x21,
	0x91, 0x80, 0xc5, 0x24, 0xf4, 0xe5, 0x5c, 0xb8, 0x7a, 0x95, 0xa6, 0x67, 0x69, 0xd6, 0x93, 0x08,
	0x6d, 0x41, 0x8d, 0x91, 0x8b, 0x80, 0x85, 0xb9, 0xc9, 0x54, 0xa6, 0xea, 0x8c, 0x6a, 0xdb, 0x06,
	0x54, 0x46, 0xd9, 0x42, 0xa5, 0xa2, 0xae, 0xa4, 0x99, 0xb6, 0x3c, 0x81, 0xb5, 0xe9, 0x64, 0xc9,
	0x6f, 0xf3, 0x2b, 0x29, 0x6b, 0x2b, 0xd7, 0x16, 0xc6, 0xb6, 0x0b, 0xeb, 0xd3, 0x81, 0xdf, 0x4d,
	0x2a, 0xab, 0xa4, 0x7f, 0x16, 0xd4, 0x79, 0xda, 0xf6, 0x7b, 0x68, 0xde, 0x7b, 0x98, 0xa8, 0x0e,
	0xd6, 0xf1, 0xe0, 0x70, 0xd8, 0xef, 0xb9, 0x2f, 0xdc, 0xfe, 0x41, 0xa3, 0x80, 0x00, 0x4a, 0x7b,
	0xbd, 0x23, 0xf7, 0xa4, 0xdf, 0x30, 0x50, 0x05, 0x56, 0xdc, 0xc1, 0x34, 0x5a, 0x42, 0x16, 0x94,
	0xdd, 0xc1, 0xc9, 0xde, 0x1b, 0xf7, 0xa0, 0xb1, 0x2c, 0x03, 0x6f, 0xef, 0xed, 0xd0, 0x1d, 0xbc,
	0x6c, 0x98, 0xfb, 0xef, 0xbe, 0xdd, 0x38, 0xc6, 0xf5, 0x8d, 0x63, 0xfc, 0xb8, 0x71, 0x8c, 0x2f,
	0xb7, 0x4e, 0xe1, 0xfa, 0xd6, 0x29, 0x7c, 0xbf, 0x75, 0x0a, 0x1f, 0x76, 0x4f, 0xa9, 0x18, 0x67,
	0xa3, 0x2e, 0x4e, 0x26, 0x3b, 0x29, 0x4b, 0xc2, 0x0c, 0x0b, 0x8e, 0xe9, 0x9d, 0x6f, 0xe6, 0x72,
	0x61, 0x2d, 0xae, 0x52, 0xc2, 0x47, 0x25, 0xf5, 0xdb, 0x3c, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff,
	0x33, 0x32, 0xac, 0xfa, 0x96, 0x04, 0x00, 0x00,
}

func (m *Participant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Participant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Participant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentEpochStats != nil {
		{
			size, err := m.CurrentEpochStats.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParticipant(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x72
	}
	if m.EpochsCompleted != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.EpochsCompleted))
		i--
		dAtA[i] = 0x68
	}
	if len(m.WorkerPublicKey) > 0 {
		i -= len(m.WorkerPublicKey)
		copy(dAtA[i:], m.WorkerPublicKey)
		i = encodeVarintParticipant(dAtA, i, uint64(len(m.WorkerPublicKey)))
		i--
		dAtA[i] = 0x62
	}
	if m.ConsecutiveInvalidInferences != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.ConsecutiveInvalidInferences))
		i--
		dAtA[i] = 0x58
	}
	if len(m.ValidatorKey) > 0 {
		i -= len(m.ValidatorKey)
		copy(dAtA[i:], m.ValidatorKey)
		i = encodeVarintParticipant(dAtA, i, uint64(len(m.ValidatorKey)))
		i--
		dAtA[i] = 0x52
	}
	if m.CoinBalance != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.CoinBalance))
		i--
		dAtA[i] = 0x48
	}
	if m.Status != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if len(m.InferenceUrl) > 0 {
		i -= len(m.InferenceUrl)
		copy(dAtA[i:], m.InferenceUrl)
		i = encodeVarintParticipant(dAtA, i, uint64(len(m.InferenceUrl)))
		i--
		dAtA[i] = 0x3a
	}
	if m.LastInferenceTime != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.LastInferenceTime))
		i--
		dAtA[i] = 0x30
	}
	if m.JoinHeight != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.JoinHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.JoinTime != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.JoinTime))
		i--
		dAtA[i] = 0x20
	}
	if m.Weight != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintParticipant(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintParticipant(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CurrentEpochStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentEpochStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentEpochStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InvalidatedInferences != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.InvalidatedInferences))
		i--
		dAtA[i] = 0x38
	}
	if m.ValidatedInferences != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.ValidatedInferences))
		i--
		dAtA[i] = 0x30
	}
	if m.BurnedCoins != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.BurnedCoins))
		i--
		dAtA[i] = 0x28
	}
	if m.RewardedCoins != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.RewardedCoins))
		i--
		dAtA[i] = 0x20
	}
	if m.EarnedCoins != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.EarnedCoins))
		i--
		dAtA[i] = 0x18
	}
	if m.MissedRequests != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.MissedRequests))
		i--
		dAtA[i] = 0x10
	}
	if m.InferenceCount != 0 {
		i = encodeVarintParticipant(dAtA, i, uint64(m.InferenceCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParticipant(dAtA []byte, offset int, v uint64) int {
	offset -= sovParticipant(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Participant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovParticipant(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovParticipant(uint64(l))
	}
	if m.Weight != 0 {
		n += 1 + sovParticipant(uint64(m.Weight))
	}
	if m.JoinTime != 0 {
		n += 1 + sovParticipant(uint64(m.JoinTime))
	}
	if m.JoinHeight != 0 {
		n += 1 + sovParticipant(uint64(m.JoinHeight))
	}
	if m.LastInferenceTime != 0 {
		n += 1 + sovParticipant(uint64(m.LastInferenceTime))
	}
	l = len(m.InferenceUrl)
	if l > 0 {
		n += 1 + l + sovParticipant(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovParticipant(uint64(m.Status))
	}
	if m.CoinBalance != 0 {
		n += 1 + sovParticipant(uint64(m.CoinBalance))
	}
	l = len(m.ValidatorKey)
	if l > 0 {
		n += 1 + l + sovParticipant(uint64(l))
	}
	if m.ConsecutiveInvalidInferences != 0 {
		n += 1 + sovParticipant(uint64(m.ConsecutiveInvalidInferences))
	}
	l = len(m.WorkerPublicKey)
	if l > 0 {
		n += 1 + l + sovParticipant(uint64(l))
	}
	if m.EpochsCompleted != 0 {
		n += 1 + sovParticipant(uint64(m.EpochsCompleted))
	}
	if m.CurrentEpochStats != nil {
		l = m.CurrentEpochStats.Size()
		n += 1 + l + sovParticipant(uint64(l))
	}
	return n
}

func (m *CurrentEpochStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.InferenceCount != 0 {
		n += 1 + sovParticipant(uint64(m.InferenceCount))
	}
	if m.MissedRequests != 0 {
		n += 1 + sovParticipant(uint64(m.MissedRequests))
	}
	if m.EarnedCoins != 0 {
		n += 1 + sovParticipant(uint64(m.EarnedCoins))
	}
	if m.RewardedCoins != 0 {
		n += 1 + sovParticipant(uint64(m.RewardedCoins))
	}
	if m.BurnedCoins != 0 {
		n += 1 + sovParticipant(uint64(m.BurnedCoins))
	}
	if m.ValidatedInferences != 0 {
		n += 1 + sovParticipant(uint64(m.ValidatedInferences))
	}
	if m.InvalidatedInferences != 0 {
		n += 1 + sovParticipant(uint64(m.InvalidatedInferences))
	}
	return n
}

func sovParticipant(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParticipant(x uint64) (n int) {
	return sovParticipant(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Participant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParticipant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Participant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Participant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinTime", wireType)
			}
			m.JoinTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JoinTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinHeight", wireType)
			}
			m.JoinHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JoinHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastInferenceTime", wireType)
			}
			m.LastInferenceTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastInferenceTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InferenceUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InferenceUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ParticipantStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinBalance", wireType)
			}
			m.CoinBalance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinBalance |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveInvalidInferences", wireType)
			}
			m.ConsecutiveInvalidInferences = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveInvalidInferences |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkerPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkerPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochsCompleted", wireType)
			}
			m.EpochsCompleted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochsCompleted |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpochStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParticipant
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CurrentEpochStats == nil {
				m.CurrentEpochStats = &CurrentEpochStats{}
			}
			if err := m.CurrentEpochStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParticipant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParticipant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CurrentEpochStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParticipant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentEpochStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentEpochStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InferenceCount", wireType)
			}
			m.InferenceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InferenceCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissedRequests", wireType)
			}
			m.MissedRequests = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MissedRequests |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarnedCoins", wireType)
			}
			m.EarnedCoins = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EarnedCoins |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardedCoins", wireType)
			}
			m.RewardedCoins = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardedCoins |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnedCoins", wireType)
			}
			m.BurnedCoins = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BurnedCoins |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatedInferences", wireType)
			}
			m.ValidatedInferences = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatedInferences |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvalidatedInferences", wireType)
			}
			m.InvalidatedInferences = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InvalidatedInferences |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParticipant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParticipant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParticipant(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParticipant
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParticipant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParticipant
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParticipant
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParticipant
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParticipant        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParticipant          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParticipant = fmt.Errorf("proto: unexpected end of group")
)
