// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/training_task.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TrainingTask struct {
	Id                             uint64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestedBy                    string                       `protobuf:"bytes,2,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	CreatedAtBlockHeight           uint64                       `protobuf:"varint,3,opt,name=created_at_block_height,json=createdAtBlockHeight,proto3" json:"created_at_block_height,omitempty"`
	Assigner                       string                       `protobuf:"bytes,4,opt,name=assigner,proto3" json:"assigner,omitempty"`
	ClaimedByAssignerAtBlockHeight uint64                       `protobuf:"varint,5,opt,name=claimed_by_assigner_at_block_height,json=claimedByAssignerAtBlockHeight,proto3" json:"claimed_by_assigner_at_block_height,omitempty"`
	AssignedAtBlockHeight          uint64                       `protobuf:"varint,6,opt,name=assigned_at_block_height,json=assignedAtBlockHeight,proto3" json:"assigned_at_block_height,omitempty"`
	FinishedAtBlockHeight          uint64                       `protobuf:"varint,7,opt,name=finished_at_block_height,json=finishedAtBlockHeight,proto3" json:"finished_at_block_height,omitempty"`
	HardwareResources              []*TrainingHardwareResources `protobuf:"bytes,8,rep,name=hardware_resources,json=hardwareResources,proto3" json:"hardware_resources,omitempty"`
	Config                         *TrainingConfig              `protobuf:"bytes,9,opt,name=config,proto3" json:"config,omitempty"`
	Assignees                      []*TrainingTaskAssignee      `protobuf:"bytes,10,rep,name=assignees,proto3" json:"assignees,omitempty"`
	Epoch                          *EpochInfo                   `protobuf:"bytes,11,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *TrainingTask) Reset()         { *m = TrainingTask{} }
func (m *TrainingTask) String() string { return proto.CompactTextString(m) }
func (*TrainingTask) ProtoMessage()    {}
func (*TrainingTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3d50542a135bda, []int{0}
}
func (m *TrainingTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainingTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainingTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainingTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingTask.Merge(m, src)
}
func (m *TrainingTask) XXX_Size() int {
	return m.Size()
}
func (m *TrainingTask) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingTask.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingTask proto.InternalMessageInfo

func (m *TrainingTask) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TrainingTask) GetRequestedBy() string {
	if m != nil {
		return m.RequestedBy
	}
	return ""
}

func (m *TrainingTask) GetCreatedAtBlockHeight() uint64 {
	if m != nil {
		return m.CreatedAtBlockHeight
	}
	return 0
}

func (m *TrainingTask) GetAssigner() string {
	if m != nil {
		return m.Assigner
	}
	return ""
}

func (m *TrainingTask) GetClaimedByAssignerAtBlockHeight() uint64 {
	if m != nil {
		return m.ClaimedByAssignerAtBlockHeight
	}
	return 0
}

func (m *TrainingTask) GetAssignedAtBlockHeight() uint64 {
	if m != nil {
		return m.AssignedAtBlockHeight
	}
	return 0
}

func (m *TrainingTask) GetFinishedAtBlockHeight() uint64 {
	if m != nil {
		return m.FinishedAtBlockHeight
	}
	return 0
}

func (m *TrainingTask) GetHardwareResources() []*TrainingHardwareResources {
	if m != nil {
		return m.HardwareResources
	}
	return nil
}

func (m *TrainingTask) GetConfig() *TrainingConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *TrainingTask) GetAssignees() []*TrainingTaskAssignee {
	if m != nil {
		return m.Assignees
	}
	return nil
}

func (m *TrainingTask) GetEpoch() *EpochInfo {
	if m != nil {
		return m.Epoch
	}
	return nil
}

type TrainingHardwareResources struct {
	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *TrainingHardwareResources) Reset()         { *m = TrainingHardwareResources{} }
func (m *TrainingHardwareResources) String() string { return proto.CompactTextString(m) }
func (*TrainingHardwareResources) ProtoMessage()    {}
func (*TrainingHardwareResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3d50542a135bda, []int{1}
}
func (m *TrainingHardwareResources) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainingHardwareResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainingHardwareResources.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainingHardwareResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingHardwareResources.Merge(m, src)
}
func (m *TrainingHardwareResources) XXX_Size() int {
	return m.Size()
}
func (m *TrainingHardwareResources) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingHardwareResources.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingHardwareResources proto.InternalMessageInfo

func (m *TrainingHardwareResources) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TrainingHardwareResources) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type TrainingConfig struct {
	Datasets              *TrainingDatasets `protobuf:"bytes,1,opt,name=datasets,proto3" json:"datasets,omitempty"`
	NumUocEstimationSteps uint32            `protobuf:"varint,2,opt,name=num_uoc_estimation_steps,json=numUocEstimationSteps,proto3" json:"num_uoc_estimation_steps,omitempty"`
}

func (m *TrainingConfig) Reset()         { *m = TrainingConfig{} }
func (m *TrainingConfig) String() string { return proto.CompactTextString(m) }
func (*TrainingConfig) ProtoMessage()    {}
func (*TrainingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3d50542a135bda, []int{2}
}
func (m *TrainingConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainingConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingConfig.Merge(m, src)
}
func (m *TrainingConfig) XXX_Size() int {
	return m.Size()
}
func (m *TrainingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingConfig proto.InternalMessageInfo

func (m *TrainingConfig) GetDatasets() *TrainingDatasets {
	if m != nil {
		return m.Datasets
	}
	return nil
}

func (m *TrainingConfig) GetNumUocEstimationSteps() uint32 {
	if m != nil {
		return m.NumUocEstimationSteps
	}
	return 0
}

type TrainingDatasets struct {
	Train string `protobuf:"bytes,1,opt,name=train,proto3" json:"train,omitempty"`
	Test  string `protobuf:"bytes,2,opt,name=test,proto3" json:"test,omitempty"`
}

func (m *TrainingDatasets) Reset()         { *m = TrainingDatasets{} }
func (m *TrainingDatasets) String() string { return proto.CompactTextString(m) }
func (*TrainingDatasets) ProtoMessage()    {}
func (*TrainingDatasets) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3d50542a135bda, []int{3}
}
func (m *TrainingDatasets) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainingDatasets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainingDatasets.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainingDatasets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingDatasets.Merge(m, src)
}
func (m *TrainingDatasets) XXX_Size() int {
	return m.Size()
}
func (m *TrainingDatasets) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingDatasets.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingDatasets proto.InternalMessageInfo

func (m *TrainingDatasets) GetTrain() string {
	if m != nil {
		return m.Train
	}
	return ""
}

func (m *TrainingDatasets) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

type TrainingTaskAssignee struct {
	Participant string   `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	NodeIds     []string `protobuf:"bytes,2,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
}

func (m *TrainingTaskAssignee) Reset()         { *m = TrainingTaskAssignee{} }
func (m *TrainingTaskAssignee) String() string { return proto.CompactTextString(m) }
func (*TrainingTaskAssignee) ProtoMessage()    {}
func (*TrainingTaskAssignee) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3d50542a135bda, []int{4}
}
func (m *TrainingTaskAssignee) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainingTaskAssignee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainingTaskAssignee.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainingTaskAssignee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingTaskAssignee.Merge(m, src)
}
func (m *TrainingTaskAssignee) XXX_Size() int {
	return m.Size()
}
func (m *TrainingTaskAssignee) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingTaskAssignee.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingTaskAssignee proto.InternalMessageInfo

func (m *TrainingTaskAssignee) GetParticipant() string {
	if m != nil {
		return m.Participant
	}
	return ""
}

func (m *TrainingTaskAssignee) GetNodeIds() []string {
	if m != nil {
		return m.NodeIds
	}
	return nil
}

type EpochInfo struct {
	LastEpoch            int32 `protobuf:"varint,1,opt,name=last_epoch,json=lastEpoch,proto3" json:"last_epoch,omitempty"`
	LastEpochBlockHeight int64 `protobuf:"varint,2,opt,name=last_epoch_block_height,json=lastEpochBlockHeight,proto3" json:"last_epoch_block_height,omitempty"`
	LastEpochTimestamp   int64 `protobuf:"varint,3,opt,name=last_epoch_timestamp,json=lastEpochTimestamp,proto3" json:"last_epoch_timestamp,omitempty"`
	LastEpochIsFinished  bool  `protobuf:"varint,4,opt,name=last_epoch_is_finished,json=lastEpochIsFinished,proto3" json:"last_epoch_is_finished,omitempty"`
}

func (m *EpochInfo) Reset()         { *m = EpochInfo{} }
func (m *EpochInfo) String() string { return proto.CompactTextString(m) }
func (*EpochInfo) ProtoMessage()    {}
func (*EpochInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3d50542a135bda, []int{5}
}
func (m *EpochInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochInfo.Merge(m, src)
}
func (m *EpochInfo) XXX_Size() int {
	return m.Size()
}
func (m *EpochInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EpochInfo proto.InternalMessageInfo

func (m *EpochInfo) GetLastEpoch() int32 {
	if m != nil {
		return m.LastEpoch
	}
	return 0
}

func (m *EpochInfo) GetLastEpochBlockHeight() int64 {
	if m != nil {
		return m.LastEpochBlockHeight
	}
	return 0
}

func (m *EpochInfo) GetLastEpochTimestamp() int64 {
	if m != nil {
		return m.LastEpochTimestamp
	}
	return 0
}

func (m *EpochInfo) GetLastEpochIsFinished() bool {
	if m != nil {
		return m.LastEpochIsFinished
	}
	return false
}

func init() {
	proto.RegisterType((*TrainingTask)(nil), "inference.inference.TrainingTask")
	proto.RegisterType((*TrainingHardwareResources)(nil), "inference.inference.TrainingHardwareResources")
	proto.RegisterType((*TrainingConfig)(nil), "inference.inference.TrainingConfig")
	proto.RegisterType((*TrainingDatasets)(nil), "inference.inference.TrainingDatasets")
	proto.RegisterType((*TrainingTaskAssignee)(nil), "inference.inference.TrainingTaskAssignee")
	proto.RegisterType((*EpochInfo)(nil), "inference.inference.EpochInfo")
}

func init() {
	proto.RegisterFile("inference/inference/training_task.proto", fileDescriptor_8a3d50542a135bda)
}

var fileDescriptor_8a3d50542a135bda = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4f, 0x4f, 0x1b, 0x39,
	0x14, 0x67, 0x48, 0x02, 0x99, 0x17, 0x16, 0xed, 0x9a, 0xb0, 0x3b, 0xac, 0xd4, 0x51, 0x1a, 0x54,
	0x35, 0xbd, 0x84, 0x0a, 0x8a, 0x7a, 0x68, 0x2f, 0xa4, 0xa5, 0x05, 0xf5, 0x50, 0xc9, 0xd0, 0x4b,
	0xa5, 0x6a, 0xe4, 0x78, 0x9c, 0x8c, 0x05, 0x63, 0x4f, 0xc7, 0x1e, 0xb5, 0xf9, 0x0e, 0x3d, 0xf4,
	0x63, 0x71, 0xe4, 0xd8, 0x63, 0x05, 0xf7, 0x7e, 0x86, 0xca, 0x8e, 0x67, 0x48, 0x20, 0xe5, 0x66,
	0xbf, 0xdf, 0x1f, 0xbf, 0x67, 0xbf, 0x67, 0x78, 0xcc, 0xc5, 0x88, 0xe5, 0x4c, 0x50, 0xb6, 0x73,
	0xb3, 0xd2, 0x39, 0xe1, 0x82, 0x8b, 0x71, 0xa4, 0x89, 0x3a, 0xeb, 0x67, 0xb9, 0xd4, 0x12, 0x6d,
	0x54, 0x70, 0xbf, 0x5a, 0x75, 0x7f, 0xd5, 0x61, 0xed, 0xd4, 0x91, 0x4f, 0x89, 0x3a, 0x43, 0xeb,
	0xb0, 0xcc, 0xe3, 0xc0, 0xeb, 0x78, 0xbd, 0x3a, 0x5e, 0xe6, 0x31, 0x7a, 0x08, 0x6b, 0x39, 0xfb,
	0x5c, 0x30, 0xa5, 0x59, 0x1c, 0x0d, 0x27, 0xc1, 0x72, 0xc7, 0xeb, 0xf9, 0xb8, 0x55, 0xc5, 0x06,
	0x13, 0xb4, 0x0f, 0xff, 0xd1, 0x9c, 0x11, 0x43, 0x20, 0x3a, 0x1a, 0x9e, 0x4b, 0x7a, 0x16, 0x25,
	0x8c, 0x8f, 0x13, 0x1d, 0xd4, 0xac, 0x4f, 0xdb, 0xc1, 0x07, 0x7a, 0x60, 0xc0, 0x23, 0x8b, 0xa1,
	0xff, 0xa1, 0x49, 0x94, 0xe2, 0x63, 0xc1, 0xf2, 0xa0, 0x6e, 0x5d, 0xab, 0x3d, 0x7a, 0x07, 0xdb,
	0xf4, 0x9c, 0xf0, 0xd4, 0x9e, 0x19, 0x95, 0xe1, 0x3b, 0xf6, 0x0d, 0x6b, 0x1f, 0x3a, 0xea, 0x60,
	0x72, 0xe0, 0x88, 0xf3, 0x07, 0x3d, 0x87, 0xc0, 0x39, 0xdc, 0x4d, 0x70, 0xc5, 0x3a, 0x6c, 0x96,
	0xf8, 0x1d, 0xe1, 0x88, 0x0b, 0xae, 0x92, 0x05, 0xc2, 0xd5, 0xa9, 0xb0, 0xc4, 0xe7, 0x85, 0x9f,
	0x00, 0x25, 0x24, 0x8f, 0xbf, 0x90, 0x9c, 0x45, 0x39, 0x53, 0xb2, 0xc8, 0x29, 0x53, 0x41, 0xb3,
	0x53, 0xeb, 0xb5, 0x76, 0xfb, 0xfd, 0x05, 0xef, 0xd0, 0x2f, 0xdf, 0xe0, 0xc8, 0xc9, 0x70, 0xa9,
	0xc2, 0xff, 0x24, 0xb7, 0x43, 0xe8, 0x05, 0xac, 0x50, 0x29, 0x46, 0x7c, 0x1c, 0xf8, 0x1d, 0xaf,
	0xd7, 0xda, 0xdd, 0xbe, 0xd7, 0xf2, 0x95, 0xa5, 0x62, 0x27, 0x41, 0x6f, 0xc1, 0x77, 0xd5, 0x32,
	0x15, 0x80, 0x4d, 0xe9, 0xc9, 0xbd, 0x7a, 0xd3, 0x16, 0xee, 0x62, 0x19, 0xbe, 0xd1, 0xa2, 0x67,
	0xd0, 0x60, 0x99, 0xa4, 0x49, 0xd0, 0xb2, 0x49, 0x84, 0x0b, 0x4d, 0x0e, 0x0d, 0xe3, 0x58, 0x8c,
	0x24, 0x9e, 0x92, 0xbb, 0x87, 0xb0, 0xf5, 0xc7, 0x5a, 0x11, 0x82, 0xba, 0x9e, 0x64, 0xcc, 0xb6,
	0x9f, 0x8f, 0xed, 0x1a, 0xb5, 0xa1, 0x41, 0x65, 0x21, 0xb4, 0xed, 0xbc, 0xbf, 0xf0, 0x74, 0xd3,
	0xfd, 0xe6, 0xc1, 0xfa, 0x7c, 0x81, 0xe8, 0x00, 0x9a, 0x31, 0xd1, 0x44, 0x31, 0xad, 0xac, 0x41,
	0x6b, 0xf7, 0xd1, 0xbd, 0x75, 0xbd, 0x76, 0x64, 0x5c, 0xc9, 0xcc, 0x83, 0x8b, 0x22, 0x8d, 0x0a,
	0x49, 0x23, 0xa6, 0x34, 0x4f, 0x89, 0xe6, 0x52, 0x44, 0x4a, 0xb3, 0x4c, 0xb9, 0xe3, 0x37, 0x45,
	0x91, 0x7e, 0x90, 0xf4, 0xb0, 0x42, 0x4f, 0x0c, 0xd8, 0x7d, 0x09, 0x7f, 0xdf, 0xb6, 0x35, 0x89,
	0xdb, 0x31, 0x74, 0xd5, 0x4c, 0x37, 0xb6, 0x44, 0xa6, 0xb4, 0x9b, 0x23, 0xbb, 0xee, 0x9e, 0x40,
	0x7b, 0xd1, 0x65, 0xa3, 0x0e, 0xb4, 0x32, 0x92, 0x6b, 0x4e, 0x79, 0x46, 0x84, 0x76, 0x3e, 0xb3,
	0x21, 0xb4, 0x05, 0x4d, 0x21, 0x63, 0x16, 0xf1, 0xd8, 0x24, 0x58, 0xeb, 0xf9, 0x78, 0xd5, 0xec,
	0x8f, 0x63, 0xd5, 0xbd, 0xf0, 0xc0, 0xaf, 0x6e, 0x1f, 0x3d, 0x00, 0x38, 0x27, 0x4a, 0x47, 0xd3,
	0x17, 0x33, 0x4e, 0x0d, 0xec, 0x9b, 0x88, 0xa5, 0x98, 0x11, 0xbe, 0x81, 0xe7, 0x1b, 0xdd, 0x24,
	0x5a, 0xc3, 0xed, 0x8a, 0x3b, 0xdb, 0xe7, 0x4f, 0xa1, 0x3d, 0x23, 0xd3, 0x3c, 0x65, 0x4a, 0x93,
	0x34, 0xb3, 0x63, 0x5f, 0xc3, 0xa8, 0xd2, 0x9c, 0x96, 0x08, 0xda, 0x83, 0x7f, 0x67, 0x14, 0x5c,
	0x45, 0xe5, 0x00, 0xd9, 0x2f, 0xa0, 0x89, 0x37, 0x2a, 0xcd, 0xb1, 0x7a, 0xe3, 0xa0, 0xc1, 0xfb,
	0x8b, 0xab, 0xd0, 0xbb, 0xbc, 0x0a, 0xbd, 0x9f, 0x57, 0xa1, 0xf7, 0xfd, 0x3a, 0x5c, 0xba, 0xbc,
	0x0e, 0x97, 0x7e, 0x5c, 0x87, 0x4b, 0x1f, 0xf7, 0xc7, 0x5c, 0x27, 0xc5, 0xb0, 0x4f, 0x65, 0xba,
	0x93, 0xe5, 0x32, 0x2e, 0xa8, 0x56, 0x94, 0xdf, 0xfa, 0x0c, 0xbf, 0xce, 0x7e, 0x8c, 0x93, 0x8c,
	0xa9, 0xe1, 0x8a, 0xfd, 0x11, 0xf7, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x93, 0xb0, 0x85,
	0x3c, 0x05, 0x00, 0x00,
}

func (m *TrainingTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainingTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainingTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != nil {
		{
			size, err := m.Epoch.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTrainingTask(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Assignees) > 0 {
		for iNdEx := len(m.Assignees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assignees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTrainingTask(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.Config != nil {
		{
			size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTrainingTask(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if len(m.HardwareResources) > 0 {
		for iNdEx := len(m.HardwareResources) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HardwareResources[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTrainingTask(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.FinishedAtBlockHeight != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.FinishedAtBlockHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.AssignedAtBlockHeight != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.AssignedAtBlockHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.ClaimedByAssignerAtBlockHeight != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.ClaimedByAssignerAtBlockHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Assigner) > 0 {
		i -= len(m.Assigner)
		copy(dAtA[i:], m.Assigner)
		i = encodeVarintTrainingTask(dAtA, i, uint64(len(m.Assigner)))
		i--
		dAtA[i] = 0x22
	}
	if m.CreatedAtBlockHeight != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.CreatedAtBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RequestedBy) > 0 {
		i -= len(m.RequestedBy)
		copy(dAtA[i:], m.RequestedBy)
		i = encodeVarintTrainingTask(dAtA, i, uint64(len(m.RequestedBy)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TrainingHardwareResources) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainingHardwareResources) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainingHardwareResources) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintTrainingTask(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TrainingConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainingConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainingConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NumUocEstimationSteps != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.NumUocEstimationSteps))
		i--
		dAtA[i] = 0x10
	}
	if m.Datasets != nil {
		{
			size, err := m.Datasets.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTrainingTask(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TrainingDatasets) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainingDatasets) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainingDatasets) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Test) > 0 {
		i -= len(m.Test)
		copy(dAtA[i:], m.Test)
		i = encodeVarintTrainingTask(dAtA, i, uint64(len(m.Test)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Train) > 0 {
		i -= len(m.Train)
		copy(dAtA[i:], m.Train)
		i = encodeVarintTrainingTask(dAtA, i, uint64(len(m.Train)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TrainingTaskAssignee) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainingTaskAssignee) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainingTaskAssignee) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NodeIds) > 0 {
		for iNdEx := len(m.NodeIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.NodeIds[iNdEx])
			copy(dAtA[i:], m.NodeIds[iNdEx])
			i = encodeVarintTrainingTask(dAtA, i, uint64(len(m.NodeIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintTrainingTask(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastEpochIsFinished {
		i--
		if m.LastEpochIsFinished {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.LastEpochTimestamp != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.LastEpochTimestamp))
		i--
		dAtA[i] = 0x18
	}
	if m.LastEpochBlockHeight != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.LastEpochBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.LastEpoch != 0 {
		i = encodeVarintTrainingTask(dAtA, i, uint64(m.LastEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTrainingTask(dAtA []byte, offset int, v uint64) int {
	offset -= sovTrainingTask(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TrainingTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTrainingTask(uint64(m.Id))
	}
	l = len(m.RequestedBy)
	if l > 0 {
		n += 1 + l + sovTrainingTask(uint64(l))
	}
	if m.CreatedAtBlockHeight != 0 {
		n += 1 + sovTrainingTask(uint64(m.CreatedAtBlockHeight))
	}
	l = len(m.Assigner)
	if l > 0 {
		n += 1 + l + sovTrainingTask(uint64(l))
	}
	if m.ClaimedByAssignerAtBlockHeight != 0 {
		n += 1 + sovTrainingTask(uint64(m.ClaimedByAssignerAtBlockHeight))
	}
	if m.AssignedAtBlockHeight != 0 {
		n += 1 + sovTrainingTask(uint64(m.AssignedAtBlockHeight))
	}
	if m.FinishedAtBlockHeight != 0 {
		n += 1 + sovTrainingTask(uint64(m.FinishedAtBlockHeight))
	}
	if len(m.HardwareResources) > 0 {
		for _, e := range m.HardwareResources {
			l = e.Size()
			n += 1 + l + sovTrainingTask(uint64(l))
		}
	}
	if m.Config != nil {
		l = m.Config.Size()
		n += 1 + l + sovTrainingTask(uint64(l))
	}
	if len(m.Assignees) > 0 {
		for _, e := range m.Assignees {
			l = e.Size()
			n += 1 + l + sovTrainingTask(uint64(l))
		}
	}
	if m.Epoch != nil {
		l = m.Epoch.Size()
		n += 1 + l + sovTrainingTask(uint64(l))
	}
	return n
}

func (m *TrainingHardwareResources) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovTrainingTask(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovTrainingTask(uint64(m.Count))
	}
	return n
}

func (m *TrainingConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Datasets != nil {
		l = m.Datasets.Size()
		n += 1 + l + sovTrainingTask(uint64(l))
	}
	if m.NumUocEstimationSteps != 0 {
		n += 1 + sovTrainingTask(uint64(m.NumUocEstimationSteps))
	}
	return n
}

func (m *TrainingDatasets) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Train)
	if l > 0 {
		n += 1 + l + sovTrainingTask(uint64(l))
	}
	l = len(m.Test)
	if l > 0 {
		n += 1 + l + sovTrainingTask(uint64(l))
	}
	return n
}

func (m *TrainingTaskAssignee) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovTrainingTask(uint64(l))
	}
	if len(m.NodeIds) > 0 {
		for _, s := range m.NodeIds {
			l = len(s)
			n += 1 + l + sovTrainingTask(uint64(l))
		}
	}
	return n
}

func (m *EpochInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastEpoch != 0 {
		n += 1 + sovTrainingTask(uint64(m.LastEpoch))
	}
	if m.LastEpochBlockHeight != 0 {
		n += 1 + sovTrainingTask(uint64(m.LastEpochBlockHeight))
	}
	if m.LastEpochTimestamp != 0 {
		n += 1 + sovTrainingTask(uint64(m.LastEpochTimestamp))
	}
	if m.LastEpochIsFinished {
		n += 2
	}
	return n
}

func sovTrainingTask(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTrainingTask(x uint64) (n int) {
	return sovTrainingTask(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TrainingTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainingTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainingTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainingTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtBlockHeight", wireType)
			}
			m.CreatedAtBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assigner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assigner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedByAssignerAtBlockHeight", wireType)
			}
			m.ClaimedByAssignerAtBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimedByAssignerAtBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssignedAtBlockHeight", wireType)
			}
			m.AssignedAtBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssignedAtBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinishedAtBlockHeight", wireType)
			}
			m.FinishedAtBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinishedAtBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HardwareResources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HardwareResources = append(m.HardwareResources, &TrainingHardwareResources{})
			if err := m.HardwareResources[len(m.HardwareResources)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Config == nil {
				m.Config = &TrainingConfig{}
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assignees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assignees = append(m.Assignees, &TrainingTaskAssignee{})
			if err := m.Assignees[len(m.Assignees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Epoch == nil {
				m.Epoch = &EpochInfo{}
			}
			if err := m.Epoch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrainingTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrainingHardwareResources) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainingTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainingHardwareResources: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainingHardwareResources: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTrainingTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrainingConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainingTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainingConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainingConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Datasets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Datasets == nil {
				m.Datasets = &TrainingDatasets{}
			}
			if err := m.Datasets.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumUocEstimationSteps", wireType)
			}
			m.NumUocEstimationSteps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumUocEstimationSteps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTrainingTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrainingDatasets) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainingTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainingDatasets: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainingDatasets: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Train", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Train = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Test", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Test = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrainingTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrainingTaskAssignee) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainingTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainingTaskAssignee: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainingTaskAssignee: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainingTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeIds = append(m.NodeIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrainingTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainingTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEpoch", wireType)
			}
			m.LastEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastEpoch |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEpochBlockHeight", wireType)
			}
			m.LastEpochBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastEpochBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEpochTimestamp", wireType)
			}
			m.LastEpochTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastEpochTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEpochIsFinished", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LastEpochIsFinished = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTrainingTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainingTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTrainingTask(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTrainingTask
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrainingTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTrainingTask
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTrainingTask
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTrainingTask
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTrainingTask        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTrainingTask          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTrainingTask = fmt.Errorf("proto: unexpected end of group")
)
